# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77a0ce500c5198e019aac197c7e96f5c6eb3437c3e96cf6f8bdb551713e52f2f031878f725775f5123b3e0dfca653fa8610d3762d248cc9da0d08c6c41af2f3a

test:
  secret_key_base: e9b771c9a6cc4240442dc936c2feead93446f78c125d7c2f357a03dff310ecf7ef7f12922d1cdcf458a6f42b16262d44cf582fd2e6ced627fdd6bf115d38c0f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
